In [2]:
import pandas as pd
import numpy as np

In [35]:
products = ['iphone', 'ipad', 'macbook']

revenue_df = pd.DataFrame({
    'Q1': [180, 24, 12],
    'Q2': [200, 36, 18],
    'Q3': [220, 40, 20]
},
index=products)

# Create expenses dataframe
expenses_df = pd.DataFrame({
    'Q1': [80, 10, 8],
    'Q2': [90, 16, 10],
    'Q3': [100, 20, 10]
},
index=products)

In [36]:
revenue_df

          Q1   Q2   Q3
iphone   180  200  220
ipad      24   36   40
macbook   12   18   20

In [37]:
expenses_df

         Q1  Q2   Q3
iphone   80  90  100
ipad     10  16   20
macbook   8  10   10

In [38]:
# Convert dataframe to numpy arrays
revenue_arr = np.array(revenue_df)
expenses_arr = np.array(expenses_df)

In [39]:
revenue_arr

array([[180, 200, 220],
       [ 24,  36,  40],
       [ 12,  18,  20]])

In [30]:
expenses_arr

array([[ 80,  90, 100],
       [ 10,  16,  20],
       [  8,  10,  10]])

In [33]:
profit_arr = revenue_arr - expenses_arr

In [34]:
profit_arr

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [42]:
revenue_df.columns

Index(['Q1', 'Q2', 'Q3'], dtype='str')

In [44]:
# We can always see the matrix in form of a dataframe in the following way
pd.DataFrame(profit_arr, index=products, columns=revenue_df.columns)

          Q1   Q2   Q3
iphone   100  110  120
ipad      14   20   20
macbook    4    8   10

In [ ]:
unitprice_df = pd.DataFrame({
    'Q1': [180, 24, 12],
    'Q2': [200, 36, 18],
    'Q3': [220, 40, 20]
},
index=products)

In [51]:
unitprice_df = pd.DataFrame(
                            [[1000, 400, 1200]],
                            columns=products,
                            index=['Unit Price']
                            )

In [52]:
unitprice_df

            iphone  ipad  macbook
Unit Price    1000   400     1200

In [53]:
unitprice_arr = np.array(unitprice_df)

In [55]:
unitprice_arr

array([[1000,  400, 1200]])

In [59]:
units_df = pd.DataFrame({
    'Q1': [30, 5, 2],
    'Q2': [40, 10, 5],
    'Q3': [50, 15, 7]
},
index=products)

In [60]:
units_df

         Q1  Q2  Q3
iphone   30  40  50
ipad      5  10  15
macbook   2   5   7

In [61]:
units_arr = np.array(units_df)

In [62]:
np.dot(unitprice_arr, units_arr )

array([[34400, 50000, 64400]])